/*===============================================================================
**  Generic Header information generated by 13521CFG.EXE (Build 4)
**  (C)SEIKO EPSON CORPORATION 2002-2007. All rights reserved.
**
** Manually edited.
**===============================================================================*/
#ifdef CONFIG_FB_EPSON_SPI
#define GPIO_CNFX	16
#define GPIO_CNF1	17

#define USE_DMA 1
#ifdef CONFIG_FB_EPSON_HRDY_OK
#define GPIO_HRDY	1
#endif

//#define GPIO_HDC	0
#define GPIO_RESET_L	76
#define GPIO_HIRQ	54
#endif

#define BSC_RD_REG( a )     s1d13522if_ReadReg16( a )
#define BSC_WR_REG( a, d )  s1d13522if_WriteReg16( a, d )
#define SFM_READ_COMMAND   0
#define SFM_CLOCK_DIVIDE   3
#define SFM_CLOCK_PHASE    0
#define SFM_CLOCK_POLARITY 0

#define INIT_PLL_CFG_0  0x0004
#define INIT_PLL_CFG_1  0x5949
#define INIT_PLL_CFG_2  0x0040
#define INIT_CLK_CFG   0x0000

#define INIT_SPI_FLASH_ACC_MODE  0 // access mode select
#define INIT_SPI_FLASH_RDC_MODE  0 // read command select
#define INIT_SPI_FLASH_CLK_DIV   3  // clock divider
#define INIT_SPI_FLASH_CLK_PHS   0 // clock phase select
#define INIT_SPI_FLASH_CLK_POL   0 // clock polarity select
#define INIT_SPI_FLASH_ENB       1 // enable
#define INIT_SPI_FLASH_CTL  (\
  ( INIT_SPI_FLASH_ACC_MODE << 7 ) | \
  ( INIT_SPI_FLASH_RDC_MODE << 6 ) |\
  ( INIT_SPI_FLASH_CLK_DIV << 3 ) |\
  ( INIT_SPI_FLASH_CLK_PHS << 2 ) |\
  ( INIT_SPI_FLASH_CLK_POL << 1 ) |\
  INIT_SPI_FLASH_ENB)

#define  INIT_SPI_FLASH_CS_ENB  1
#define  INIT_SPI_FLASH_CSC   INIT_SPI_FLASH_CS_ENB

#define BS_SFM_SECTOR_COUNT 128
#define BS_SFM_SECTOR_SIZE  (4*1024)
#define BS_SFM_PAGE_SIZE    256
#define BS_SFM_PAGE_COUNT   2048

#define BS_SFM_WREN 0x06
#define BS_SFM_WRDI 0x04

#define BS_SFM_RDSR 0x05
#define BS_SFM_READ 0x03

#define BS_SFM_PP   0x02
#define BS_SFM_SE   0x20



#define ROUNDUP16(X)  ((X+0x0f)&~0x0f)
#define S1D_13522
#define S1D_DISPLAY_WIDTH              540
#define S1D_DISPLAY_HEIGHT              960
#define S1D_DISPLAY_BPP                 4
#define S1D_DISPLAY_SCANLINE_BYTES      600
#define S1D_DISPLAY_FRAME_RATE          0
#define S1D_DISPLAY_PCLK                26400000L
#define S1D_PHYSICAL_REG_ADDR           0x00000000L
#define S1D_PHYSICAL_REG_SIZE           90L
#define S1D_PHYSICAL_VMEM_REQUIRED      640000L
#define S1D_PALETTE_SIZE                256
#define S1D_POWER_DELAY_OFF             0
#define S1D_POWER_DELAY_ON              0

#define FLASH_CMD_ADDR  0x0000


#define FLASH_WF_ADDR  0x00886
#define FLASH_TEST_ADDR  0x30050

#define S1D_WF_ADDR   0xbdd80L
//#define S1D_WF_ADDR   0x56400L
//#define S1D_IMG_ADDR  0x76400L
#define S1D_IMG_ADDR  0xddd80L
#define S1D_PIP_ADDR   (S1D_IMG_ADDR+((ROUNDUP16(S1D_DISPLAY_WIDTH)*S1D_DISPLAY_HEIGHT*S1D_DISPLAY_BPP)/8))

//#define BIT(n)	(1UL<<(n))
#define SF_BORDERADDR	0x70008
#define SF_VCOMADDR	0x70010
#define S1D_CSR_ADDR	0x00L

#define BS60_INIT_ROTMODE       1	// rotation mode = 90 degrees

#if 0 /* legacy values */
#define WF_MODE_INIT            0
#define WF_MODE_MU              1
#define WF_MODE_GC16            2	//16 grays (flashing)
#define WF_MODE_GC4             3	//4 grays (flashing)
#define WF_MODE_A2             4	// A2
#define WF_MODE_AUTO             5	// Auto mode
#endif

/* Regal values */
#define WF_MODE_INIT                    0
#define WF_MODE_DU                              1
#define WF_MODE_GC16                    2       //16 grays (flashing)
#define WF_MODE_GL16                    3
#define WF_MODE_GLR16                   4
#define WF_MODE_GLD16                   5
#define WF_MODE_A2                              6
#define WF_MODE_DU4                             7
#define WF_MODE_AUTO                    8       // Auto mode

#define WF_MODE_USER                 20      //waveform passed via sysfs
